script: neovim before applying and fix nvim miniconda config

diff --git a/.chezmoiscripts/run_onchange_before_06-neovim.sh.tmpl b/.chezmoiscripts/run_onchange_before_06-neovim.sh.tmpl
--- a/.chezmoiscripts/run_onchange_before_06-neovim.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_before_06-neovim.sh.tmpl
@@ -1,17 +1,29 @@
 #!/bin/bash
 
+# Source nvm
+export NVM_DIR="$HOME/.nvm"
+if [ -s "$NVM_DIR/nvm.sh" ]; then
+    . "$NVM_DIR/nvm.sh"
+    nvm use node > /dev/null
+else
+    echo "=== nvm is not installed or nvm.sh is missing"
+    exit 1
+fi
+
+# Source Miniconda
+if [ -f "$HOME/.miniconda3/etc/profile.d/conda.sh" ]; then
+    . "$HOME/.miniconda3/etc/profile.d/conda.sh"
+    conda activate base
+else
+    echo "=== Miniconda is not installed or conda.sh is missing"
+    exit 1
+fi
+
+# Now enable strict error handling
 set -eufo pipefail
 
 printf "=================================================\n"
-printf "=== Chezmoi After 01 - Install Neovim\n"
-
-# Source our new .zshrc
-if [ -f "$HOME/.zshrc" ]; then
-    printf "=== Sourcing zshrc to apply latest changes\n"
-    source "$HOME/.zshrc"
-else
-    printf "=== .zshrc somehow not found. Skipping sourcing.\n"
-fi
+printf "=== Chezmoi Before 06 - Install Neovim\n"
 
 # Install Neovim if not already installed
 if ! command -v nvim &> /dev/null; then
@@ -22,11 +34,8 @@ if ! command -v nvim &> /dev/null; then
         sudo apt-get update
         sudo apt-get install -y neovim
 
-        # Prerequisites for the Python modules
-        sudo apt-get install -y python3-dev python3-pip
-
-        # Install wl-clipboard and xclip if not in a headless environment
         {{ if not .headless }}
+        # Install wl-clipboard and xclip if not in a headless environment
             sudo apt-get install -y wl-clipboard xclip
         {{ end }}
     {{ else if eq .os_id "darwin" }}
@@ -48,25 +57,15 @@ fi
 # Install pip packages
 if command -v pip3 &> /dev/null; then
     printf "=== Installing nvim pip packages: pynvim\n"
-    {{ if eq .os_id "linux-ubuntu" }}
-        sudo apt-get install -y python3-pynvim
-    {{ else }}
-        pip3 install --user pynvim
-    {{ end }}
+    pip3 install pynvim
+
     # Install additional pip packages if not in a headless environment
     {{ if not .headless }}
         printf "=== Installing overleaf pip packages: tornado, requests, intervaltree, beautifulsoup4\n"
-        pip3 install --user tornado requests intervaltree beautifulsoup4
+        pip3 install tornado requests intervaltree beautifulsoup4
     {{ end }}
 else
     printf "=== pip3 is not installed for neovim python packages\n"
-fi
-
-# Apply neovim zshrc configuration
-if command -v chezmoi &> /dev/null; then
-    chezmoi apply $HOME/.zshrc
-else
-    printf "=== Cannot find chezmoi inside this chezmoi script\n"
 fi
 
 printf "\n=== Neovim installation complete\n"
