scripts: lua install 5.1.5

diff --git a/.chezmoiscripts/run_onchange_before_05-lua-luarocks.sh.tmpl b/.chezmoiscripts/run_onchange_before_05-lua-luarocks.sh.tmpl
--- a/.chezmoiscripts/run_onchange_before_05-lua-luarocks.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_before_05-lua-luarocks.sh.tmpl
@@ -3,22 +3,33 @@
 set -eufo pipefail
 
 printf "=================================================\n"
-printf "=== Chezmoi Before 05 - Install Luarocks\n"
+printf "=== Chezmoi Before 05 - Install Lua and Luarocks\n"
 
-# Install Luarocks if not already installed
-if ! command -v luarocks &> /dev/null; then
+# Install Lua if not already installed
+if ! command -v lua &> /dev/null; then
+    # Get the latest Lua version dynamically
+    # if ! LUA_VERSION=$(curl -s https://www.lua.org/ftp/ | grep -oP 'lua-\d+\.\d+\.\d+\.tar\.gz' | sort -V | tail -n 1 | sed 's/\.tar\.gz//'); then
+    #     printf "=== Failed to get latest lua version, defaulting to installing version 5.4.7\n"
+    #     LUA_VERSION="lua-5.4.7"
+    # fi
+
+    # Get Lua version that is compatible with Neovim
+    LUA_VERSION="lua-5.1.5"
+
     {{ if eq .chezmoi.os "darwin" }}
-        brew install luarocks
+        curl -R -O https://www.lua.org/ftp/${LUA_VERSION}.tar.gz
+        tar -zxf ${LUA_VERSION}.tar.gz
+        cd ${LUA_VERSION}
+        make macosx
+        sudo make install
+        cd ..
+        rm -rf ${LUA_VERSION} ${LUA_VERSION}.tar.gz
+
     {{ else if eq .chezmoi.os "linux" }}
         # Install dependencies for Lua and Luarocks
         sudo apt-get update
         sudo apt-get install -y build-essential libreadline-dev unzip
 
-        # Get the latest Lua version dynamically
-        if ! LUA_VERSION=$(curl -s https://www.lua.org/ftp/ | grep -oP 'lua-\d+\.\d+\.\d+\.tar\.gz' | sort -V | tail -n 1 | sed 's/\.tar\.gz//'); then
-            printf "=== Failed to get latest lua version, defaulting to installing version 5.4.7\n"
-            LUA_VERSION="lua-5.4.7"
-        fi
         curl -R -O https://www.lua.org/ftp/${LUA_VERSION}.tar.gz
         tar -zxf ${LUA_VERSION}.tar.gz
         cd ${LUA_VERSION}
@@ -27,6 +38,16 @@ if ! command -v luarocks &> /dev/null; then
         cd ..
         rm -rf ${LUA_VERSION} ${LUA_VERSION}.tar.gz
 
+    {{ end }}
+else
+    printf "=== Lua is already installed\n"
+fi
+
+# Install Luarocks if not already installed
+if ! command -v luarocks &> /dev/null; then
+    {{ if eq .chezmoi.os "darwin" }}
+        brew install luarocks
+    {{ else if eq .chezmoi.os "linux" }}
         # Get the latest Luarocks version dynamically
         if ! LUAROCKS_VERSION=$(curl -s https://luarocks.github.io/luarocks/releases/ | grep -oP 'luarocks-\d+\.\d+\.\d+\.tar\.gz' | sort -V | tail -n 1 | sed 's/\.tar\.gz//'); then
             printf "=== Failed to get latest luarocks version, defaulting to installing version 3.11.1\n"
@@ -45,7 +66,7 @@ else
     printf "=== Luarocks is already installed\n"
 fi
 
-printf "\n=== Luarocks installation complete\n"
+printf "\n=== Lua and Luarocks installation complete\n"
 printf "=================================================\n"
 
 {{- /* vim: set filetype=sh: */ -}}
